### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by weiqiangt** [fztfztfzt/HearthStoneRobot#1]
炉石传说程序所在文件夹有一个日志文件，里面有很多当前牌桌的状态信息，很多记牌器就是根据那个文件来记牌。

**Comment by fztfztfzt** [comment]
@ttaanngg 找了好久都没找到这样的日志文件，官方的记牌器据说是用抓包的方法。能提示下这个日志文件的具体位置吗？谢谢

**Comment by weiqiangt** [comment]
Mac是在/Applications/HearthStone/Logs/

一般在游戏运行时会出现，有Zone.log, Arena.Log等好几个文件， Zone.log纪录了战场的所有动作

**Comment by fztfztfzt** [comment]
@ttaanngg 多谢，Windows也在安装目录下的Logs文件中，之前没找到，后来用everything搜索才看到（奇怪）。
