### ISSUE TITLE
话说还有没有其它读取炉石数据的解决方案

### ISSUE THREAD

**Issue by y1yang0** [fztfztfzt/HearthStoneRobot#2]
感觉用OpenCV图像识别太麻烦了也不优雅，请问还有没有其他读取炉石数据的方法？

比如网易炉石盒子是怎么读取数据的

**Comment by fztfztfzt** [comment]
@racaljk 有，如果你是想写AI的话，炉石安装文件夹下有个log文件夹，里面有每局的信息，很全的信息

**Comment by y1yang0** [comment]
![ss](https://cloud.githubusercontent.com/assets/5010047/15990690/edc5d248-30cd-11e6-876f-e69b5b278c7a.png)
没有LogFolder

**Comment by fztfztfzt** [comment]
我开始也没找到，后来折腾半天用everything搜索才看到的，后来一直都在了

**Comment by y1yang0** [comment]
还是没有找到，只有一个output_log.txt...

难以置信

**Comment by fztfztfzt** [comment]
![image](https://cloud.githubusercontent.com/assets/8979076/15990861/3f57ca8a-30d3-11e6-9840-5b0ac6e364da.png)
![Uploading image.png…]()

**Comment by fztfztfzt** [comment]
你可以按这个路径直接读取看看
![image](https://cloud.githubusercontent.com/assets/8979076/15990868/7373830e-30d3-11e6-9c4c-2386b7180aa0.png)

**Comment by y1yang0** [comment]
读取失败了

这会不会是你的其他软件生成的记录,毕竟我觉得暴雪做这种本地记录意义不大.

**Comment by fztfztfzt** [comment]
你用everything搜搜试试吧，我是用这个搜到的。

**Comment by fztfztfzt** [comment]
另外，mac下直接就有。。。

**Comment by y1yang0** [comment]
everything还是无解...

**Comment by fztfztfzt** [comment]
对啦，有个炉石传说记牌器的开源项目，就是读取本地log的，你可以去看看
https://github.com/HearthSim/Hearthstone-Deck-Tracker

**Comment by y1yang0** [comment]
嗯，我有空去看看
